---
- name: listicles
  gather_facts: no
  hosts: csr
  tasks:
    - name: ios poop chute
      vars:
        credentials:
            host: "{{ ansible_host }}"
            username: "{{ username }}"
            password: "{{ password }}"
      ios_facts:
        provider: "{{ credentials }}"
      register: ios_facts_output
    - name: Print stuff
      debug:
        msg: "{{ item }}"
      with_items: "{{ ansible_net_all_ipv4_addresses }}"
